#!/bin/sh

export CFLAGS=
export LDFLAGS= 
export INSTALLS=${1:-$(pwd)/installs}

echo "building libreadstat.a"
cd libreadstat; ./autogen.sh && ./configure CFLAGS= --prefix=${INSTALLS} && make && make install
